# Generated by Django 5.0.6 on 2024-07-27 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apprenant',
            fields=[
                ('matricule', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('postnom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('genre', models.CharField(max_length=1)),
                ('etatcivil', models.CharField(max_length=25)),
                ('addresse', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('profession', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='ImageProfilApprenant/')),
            ],
            options={
                'db_table': 'Apprenant',
            },
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Domaine',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('matricule', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('postnom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('genre', models.CharField(max_length=1)),
                ('etatcivil', models.CharField(max_length=25)),
                ('addresse', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('profession', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='ImageProfilEnseignant/')),
            ],
            options={
                'db_table': 'Enseignant',
            },
        ),
        migrations.CreateModel(
            name='ModalitePaie',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('tranche', models.CharField(max_length=25)),
                ('montant_fixe', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ModalitePaie',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Niveau',
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
                ('contenu', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Ressource',
            },
        ),
        migrations.CreateModel(
            name='TypeRessource',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'TypeRessource',
            },
        ),
        migrations.CreateModel(
            name='CompteUtilisateur',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, upload_to='Image/')),
                ('fonction', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=50)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.apprenant')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.enseignant')),
            ],
            options={
                'db_table': 'CompteUtilisateur',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=50)),
                ('duree', models.TimeField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.enseignant')),
            ],
            options={
                'db_table': 'Formation',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('maximum', models.DecimalField(decimal_places=1, max_digits=10)),
                ('cote', models.DecimalField(decimal_places=1, max_digits=10)),
                ('date_evaluation', models.DateTimeField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.formation')),
            ],
            options={
                'db_table': 'Evaluation',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('date_inscription', models.DateTimeField()),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.apprenant')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.formation')),
                ('modalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.modalitepaie')),
            ],
            options={
                'db_table': 'Inscription',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.formation')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.niveau')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.ressource')),
            ],
            options={
                'db_table': 'Module',
            },
        ),
        migrations.AddField(
            model_name='modalitepaie',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.module'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField()),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.apprenant')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.module')),
            ],
            options={
                'db_table': 'Paiement',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('date_publication', models.DateTimeField()),
                ('compte_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.compteutilisateur')),
            ],
            options={
                'db_table': 'Publication',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=50)),
                ('reponse', models.CharField(max_length=50)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.module')),
            ],
            options={
                'db_table': 'Questionnaire',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('reponse', models.CharField(max_length=100)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.apprenant')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.questionnaire')),
            ],
            options={
                'db_table': 'Test',
            },
        ),
        migrations.AddField(
            model_name='ressource',
            name='type_ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.typeressource'),
        ),
    ]
