# Generated by Django 3.2 on 2024-08-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sous_chapitre',
            name='titre',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
