# Generated by Django 3.2 on 2024-08-08 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compteutilisateur',
            name='photo',
        ),
        migrations.AlterField(
            model_name='compteutilisateur',
            name='apprenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eScholar.apprenant'),
        ),
        migrations.AlterField(
            model_name='compteutilisateur',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eScholar.enseignant'),
        ),
    ]
