# Generated by Django 3.2 on 2024-08-07 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='domaine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eScholar.domaine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ressource',
            name='contenu',
            field=models.FileField(max_length=500, upload_to='Ressource/'),
        ),
    ]
