# Generated by Django 3.2 on 2024-08-13 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0002_sous_chapitre_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='formation',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eScholar.module'),
            preserve_default=False,
        ),
    ]
