# Generated by Django 3.2 on 2024-08-08 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0002_auto_20240808_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='compte_utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eScholar.compteutilisateur'),
            preserve_default=False,
        ),
    ]
