# Generated by Django 3.2 on 2024-08-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0003_publication_compte_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='reponse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='reponse',
            field=models.TextField(),
        ),
    ]
