# Generated by Django 3.2 on 2024-08-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0003_auto_20240813_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='maxima',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
