# Generated by Django 3.2 on 2024-08-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0004_questionnaire_maxima'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='description',
        ),
    ]
