# Generated by Django 3.2 on 2024-08-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0004_auto_20240808_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='duree',
            field=models.CharField(max_length=20),
        ),
    ]
