# Generated by Django 3.2 on 2024-08-10 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0005_alter_formation_duree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sous_chapitre',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
            ],
            options={
                'db_table': 'Sous_chapitre',
            },
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='compte_utilisateur',
            new_name='user',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='apprenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eScholar.apprenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='titre',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='eScholar.publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Like',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='eScholar.publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Commentaire',
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('sous_chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.sous_chapitre')),
            ],
            options={
                'db_table': 'Chapitre',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='chapitre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eScholar.chapitre'),
            preserve_default=False,
        ),
    ]
