# Generated by Django 3.2 on 2024-08-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0005_remove_chapitre_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='sous_chapitre',
        ),
        migrations.CreateModel(
            name='ContenuChapitre',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.chapitre')),
                ('sous_chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.sous_chapitre')),
            ],
            options={
                'db_table': 'ContenuChapitre',
            },
        ),
    ]
