# Generated by Django 3.2 on 2024-08-13 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0007_reponses_alternatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='reponse_alternative',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eScholar.reponses_alternatives'),
            preserve_default=False,
        ),
    ]
