# Generated by Django 3.2 on 2024-08-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0007_alter_evaluation_apprenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
