# Generated by Django 5.1 on 2024-08-21 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0008_test_reponse_alternative'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprenant',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscription',
            name='modalite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eScholar.modalitepaie'),
        ),
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150)),
                ('date_interro', models.DateField()),
                ('duree', models.TimeField()),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.module')),
            ],
            options={
                'db_table': 'Interrogation',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('date_participation', models.DateField()),
                ('cote_obtenu', models.DecimalField(decimal_places=2, max_digits=2)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.apprenant')),
                ('interrogation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.interrogation')),
            ],
            options={
                'db_table': 'Participation',
            },
        ),
        migrations.CreateModel(
            name='QuestionInterrogation',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('enonce', models.TextField()),
                ('interrogation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.interrogation')),
            ],
            options={
                'db_table': 'QuestionInterrogation',
            },
        ),
        migrations.CreateModel(
            name='ReponseInterrogation',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('texte', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.questioninterrogation')),
            ],
            options={
                'db_table': 'ReponseInterrogation',
            },
        ),
    ]
