# Generated by Django 3.2 on 2024-08-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0008_auto_20240810_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, upload_to='publication/'),
        ),
    ]
