# Generated by Django 5.1 on 2024-08-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0009_apprenant_email_alter_inscription_modalite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date_inscription',
            field=models.DateField(auto_now=True),
        ),
    ]
