# Generated by Django 3.2 on 2024-08-11 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0009_publication_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='apprenant',
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eScholar.compteutilisateur'),
            preserve_default=False,
        ),
    ]
