# Generated by Django 3.2 on 2024-08-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0010_auto_20240811_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='titre',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
