# Generated by Django 5.1 on 2024-08-21 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0010_alter_inscription_date_inscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='questionnaire',
        ),
        migrations.RemoveField(
            model_name='test',
            name='reponse',
        ),
        migrations.RemoveField(
            model_name='test',
            name='reponse_alternative',
        ),
        migrations.AddField(
            model_name='test',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eScholar.module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='resultat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
