# Generated by Django 5.1 on 2024-08-22 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0011_remove_test_questionnaire_remove_test_reponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interrogation',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.enseignant'),
        ),
    ]
