# Generated by Django 3.2 on 2024-08-12 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0011_chapitre_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='formation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eScholar.formation'),
        ),
    ]
