# Generated by Django 5.1 on 2024-08-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0012_alter_interrogation_enseignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioninterrogation',
            name='maxima',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questioninterrogation',
            name='reponse',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
