# Generated by Django 3.2 on 2024-08-12 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0012_alter_inscription_formation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='module',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='formation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eScholar.formation'),
            preserve_default=False,
        ),
    ]
