# Generated by Django 5.1 on 2024-08-22 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0013_questioninterrogation_maxima_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponsesAlternativesInterro',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('reponse_alternative', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScholar.questioninterrogation')),
            ],
            options={
                'db_table': 'ReponsesAlternativesInterro',
            },
        ),
    ]
