# Generated by Django 3.2 on 2024-08-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0014_auto_20240812_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='ressource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eScholar.ressource'),
        ),
    ]
