# Generated by Django 5.1 on 2024-08-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0015_remove_interrogation_module_interrogation_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='cote_obtenu',
            field=models.IntegerField(),
        ),
    ]
