# Generated by Django 5.1 on 2024-08-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScholar', '0017_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
